#!/usr/bin/env bash

. `dirname "$0"`/tools/platform.sh
if test -f `dirname "$0"`"/tools/$KORE_PLATFORM/icon.png"; then
git -C `dirname "$0"` submodule update --remote --merge "tools/$KORE_PLATFORM"
else
git -C `dirname "$0"` submodule update --init --remote "tools/$KORE_PLATFORM"
git -C `dirname "$0"`/tools/$KORE_PLATFORM checkout main
fi