name: Android (OpenGL)

on:
  push:
    branches:
    - v1
  pull_request:
    branches:
    - v1

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
    - name: Get Submodules
      run: ./get_dlc
    - name: Compile
      run: ./make android -g opengl --kore . --from Tests/Empty --compile
