name: Emscripten (WebGPU)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: ./get_dlc
    - name: Compile (kmake)
      run: ./make emscripten -g webgpu --kinc . --from Tests/Empty
    - name: Compile (emscripten)
      run: git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh && cd ../build/Release && make
