name: Emscripten (WebGL)

on:
  push:
    branches:
    - v1
  pull_request:
    branches:
    - v1

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: ./get_dlc
    - name: Compile (kmake)
      run: ./make emscripten --kore . --from Tests/Empty
    - name: Compile (emscripten)
      run: git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && ./emsdk install latest && ./emsdk activate latest && source ./emsdk_env.sh && cd ../build/release && make
