name: Format Code for v3

on:
  schedule:
  - cron: '0 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: v3
        fetch-depth: 0

    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"

    - name: Format the code
      run: node ./.github/format.js
    - name: Add
      run: git add .
    - name: Commit
      id: commit
      continue-on-error: true
      run: git commit -m "Format C"
    - name: Push
      if: steps.commit.outcome == 'success'
      continue-on-error: true
      run: git push
