name: FreeBSD (OpenGL)

on:
  push:
    branches:
    - main
    - FreeBSD  # REMEMBER TO DELETE THIS LINE BEFORE PRRRRRRing!!!!!
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macos-12
    name: FreeBSD build

    steps:
    - uses: actions/checkout@v2
    - name: Get Kinc
      run: git submodule update --init
    - name: Get Tools
      run: git -C Kinc submodule update --init Tools/freebsd_x64
    - name: Compile in FreeBSD VM
      id: build
      uses: vmactions/freebsd-vm@v0.2.0
      with:
        usesh: true
        copyback: false
        mem: 2048
        prepare: pkg install -y bash alsa-lib libXinerama mesa-libs libXi xorg-vfbserver libXrandr libXi libXcursor evdev-proto libinotify ImageMagick7-nox11 libxkbcommon
        run: |
          echo " * Compile"
          echo `ls`
          echo `pwd`
          ./make -g opengl --kinc . --from Tests/Empty --compile
