name: iOS (Metal)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.3'

    - name: Get Submodules
      run: ./get_dlc
    - name: Compile
      run: ./make ios -g metal --kore . --from tests/empty --nosigning --compile
