name: Linux on ARM (OpenGL)

on:
  push:
    branches:
    - v1
  pull_request:
    branches:
    - v1

jobs:
  build:

    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Apt Update
      run: sudo apt update
    - name: Apt Install
      run: sudo apt-get install libasound2-dev libxinerama-dev libxrandr-dev libgl1-mesa-dev libxi-dev libxcursor-dev libudev-dev libwayland-dev wayland-protocols libxkbcommon-dev ninja-build --yes --quiet
    - name: Get Submodules
      run: ./get_dlc
    - name: Compile
      run: ./make -g opengl --kore . --from Tests/Empty --compile
    
