name: Update main

on:
  push:
    branches:
    - v2

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"

    - name: Git Checkout
      run: git checkout v2
    - name: Push to main
      run: git push origin v2:main
