name: Windows (Direct3D 11)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get Submodules
      run: .\get_dlc.bat
    - name: Compile
      run: .\make.bat -v vs2022 -g direct3d11 --kore . --from Tests/Empty --compile
    - name: Get ImageMagick
      run: |
        choco install -y imagemagick.app --no-progress
        Get-ChildItem -Path "${env:ProgramFiles}" | Where-Object {($_.Name -Like 'ImageMagick*')} | % { $_.FullName } | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
    - name: Compile and run Test 1
      run: .\make.bat -v vs2022 -g direct3d11 --kore . --from Tests/Shader --run
    - name: Check Test 1
      run: magick compare -metric mae .\Tests\Shader\reference.png .\Tests\Shader\Deployment\test.png difference.png
    - name: Compile and run Test 2 (SIMD)
      run: .\make.bat -v vs2022 --kore . --from Tests/SIMD --compile --run
