name: Windows (Direct3D 9)

on:
  push:
    branches:
    - v1
  pull_request:
    branches:
    - v1

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: .\get_dlc.bat
    - name: Install DirectX
      run: choco install -y directx --no-progress
    - name: Compile
      run: .\make.bat -v vs2022 -g direct3d9 -a directsound --kore . --from Tests/Empty --compile
