name: Windows (Vulkan)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Vulkan
      run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.275.0/windows/VulkanSDK-1.3.275.0-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("--da", "--al", "-c", "in");
          $installer.WaitForExit();
    - name: Get Submodules
      run: .\get_dlc.bat
    - name: Compile
      run: .\make.bat -v vs2022 -g vulkan --kinc . --from Tests/Empty --compile
      env:
        VULKAN_SDK: C:\VulkanSDK\1.3.275.0
