name: Windows (OpenGL)

on:
  push:
    branches:
    - v2
  pull_request:
    branches:
    - v2

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Get Submodules
      run: .\get_dlc.bat
    - name: Compile
      run: .\make.bat -v vs2022 -g opengl --kore . --from Tests/Empty --compile
